import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
const html=await readFile(new URL('../../bridge/internal/world/web/index.html',import.meta.url),'utf8');
const script=await readFile(new URL('../../bridge/internal/world/web/app.js',import.meta.url),'utf8');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function fixture(){return {player:'alice',identity:{authority:'authority-a'},operator:false,ready:true,engine_online:true,capabilities:['world.read','world.build','world.destroy'],events:[],grants:[],frame:{layers:['s'.repeat(1225),...'aaa'.split('').map(()=> 'a'.repeat(1225))],players:[{name:'alice',x:0,y:6.5,z:0}],results:[]}};}
async function page({authenticated=true}={}){
 const dom=new JSDOM(html,{url:'http://127.0.0.1:8789/play/'+(authenticated?'#session=test-session':''),runScripts:'outside-only',pretendToBeVisual:true});
 const {window:w}=dom;let data=fixture(),failure=null;const calls=[],frames=[],intervals=[],draws=[];
 w.AbortSignal=AbortSignal;
 w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({}, {get:(_,name)=>name==='createLinearGradient'?()=>({addColorStop(){}}):(...args)=>draws.push([name,...args]),set:()=>true});
 w.document.getElementById('world').getBoundingClientRect=()=>({width:900,height:600,left:0,top:0});
 w.requestAnimationFrame=fn=>{frames.push(fn);return frames.length;};w.setInterval=fn=>{intervals.push(fn);return intervals.length;};
 w.fetch=async(path,options)=>{const body=options.body?JSON.parse(options.body):undefined;calls.push({path,options,body});if(failure)return {ok:false,status:failure.status,json:async()=>({error:failure.message})};return {ok:true,status:200,json:async()=>path.endsWith('/login')?{token:'new-session'}:path.endsWith('/state')?structuredClone(data):{id:'command-1'}};};
 w.eval(script);await tick();
 return {w,calls,frames,intervals,draws,setData(v){data=v;},fail(v){failure=v;},close(){dom.window.close();}};
}
test('authenticated live scene displays permissions and renders server tiles',async()=>{const p=await page();try{assert.equal(p.w.location.hash,'');assert.equal(p.w.document.getElementById('login-panel').hidden,true);assert.equal(p.w.document.getElementById('entry').textContent,'LOCKED');assert.equal(p.w.document.getElementById('identity-name').textContent,'alice');p.frames.shift()();assert.ok(p.draws.filter(d=>d[0]==='fill').length>=1225);assert.equal(p.calls[0].options.headers.Authorization,'Bearer test-session');}finally{p.close();}});
test('a short keyboard tap sends one bounded movement command',async()=>{const p=await page();try{p.w.document.dispatchEvent(new p.w.KeyboardEvent('keydown',{key:'d',bubbles:true}));p.w.document.dispatchEvent(new p.w.KeyboardEvent('keyup',{key:'d',bubbles:true}));await tick();const moves=p.calls.filter(c=>c.path.endsWith('/command'));assert.equal(moves.length,1);assert.deepEqual(moves[0].body,{action:'move',x:1,z:0,material:''});}finally{p.close();}});
test('keyboard does not control the player while typing a password',async()=>{const p=await page({authenticated:false});try{p.w.document.getElementById('password').dispatchEvent(new p.w.KeyboardEvent('keydown',{key:'d',bubbles:true}));await tick();assert.equal(p.calls.length,0);}finally{p.close();}});
test('expired session removes controls and shows sign-in',async()=>{const p=await page();try{p.fail({status:401,message:'Sign in to play'});await p.intervals[0]();await tick();assert.equal(p.w.document.getElementById('login-panel').hidden,false);assert.equal(p.w.sessionStorage.getItem('world-session'),null);}finally{p.close();}});
test('hotbar click targets a nearby real-world tile with the selected material',async()=>{const p=await page();try{p.frames.shift()();p.w.document.querySelector('[data-tool="wood"]').click();const t=900/79,ox=450-16*t,oy=600*.43-16*t/2;const canvas=p.w.document.getElementById('world');canvas.dispatchEvent(new p.w.MouseEvent('click',{clientX:ox+2*t,clientY:oy+t,bubbles:true}));await tick();const cmd=p.calls.find(c=>c.path.endsWith('/command'));assert.equal(cmd.body.action,'place');assert.equal(cmd.body.material,'wood');assert.equal(cmd.body.x,2);assert.equal(cmd.body.z,0);}finally{p.close();}});
test('untrusted activity text is rendered without executable markup',async()=>{const p=await page();try{const d=fixture();d.frame.results=[{id:'x',player:'alice',ok:false,message:'<img src=x onerror=alert(1)>'}];p.setData(d);await p.intervals[0]();assert.equal(p.w.document.querySelectorAll('#activity img').length,0);assert.match(p.w.document.getElementById('activity').textContent,/<img/);}finally{p.close();}});
test('clicking a raised block selects that block rather than the floor behind it',async()=>{const p=await page();try{const d=fixture(),idx=12*49+2+8;d.frame.layers[1]=d.frame.layers[1].slice(0,idx)+'w'+d.frame.layers[1].slice(idx+1);p.setData(d);await p.intervals[0]();p.frames.shift()();p.w.document.querySelector('[data-tool="dig"]').click();const t=900/79,ox=450-16*t,oy=600*.43-16*t/2;p.w.document.getElementById('world').dispatchEvent(new p.w.MouseEvent('click',{clientX:ox+2*t,clientY:oy+t-t*.9,bubbles:true}));await tick();const cmd=p.calls.find(c=>c.path.endsWith('/command'));assert.equal(cmd.body.action,'dig');assert.equal(cmd.body.x,2);assert.equal(cmd.body.z,0);}finally{p.close();}});
