'use strict';
const challenges=[
 {title:'Your identity travels',tag:'01 / PASSPORT',text:'Verify your signed identity. Walk east into the locked gold court, then borrow entry from the other authority and cross the boundary.',proofs:['identity','gate_denied','cross_authority','entered'],actions:[['identity','Verify identity'],['passport','Borrow passport · 90s']]},
 {title:'Permission to create',tag:'02 / CAPABILITIES',text:'Inside the court, borrow a building lease. Select a material and place a block nearby. A real game acknowledgement completes this challenge.',proofs:['built','revoked_denied'],actions:[['build','Borrow build · 60s'],['revoke','Revoke my leases']]},
 {title:'Trust has boundaries',tag:'03 / DELEGATION',text:'Create a 90s parent and a narrower 45s child lease. Revoke the parent: the child must lose its authority too. This replaces your experiment entry leases.',proofs:['delegation','cascade_revoked','scope_blocked'],actions:[['delegate','Create delegation'],['cascade','Revoke parent'],['scope','Try forbidden scope']]},
 {title:'Nothing lasts forever',tag:'04 / EXPIRY',text:'Start a 12-second entry lease. Watch the countdown and the permission badge. The world removes access when the lease ends.',proofs:['expired'],actions:[['expiry','Start expiry challenge']]},
 {title:'Evidence survives',tag:'05 / INTEGRITY + RECOVERY',text:'Alter a copy of your identity to test signature rejection. After revoking a lease, restore an isolated database copy and replay an authentic older feed against the held floor.',proofs:['tamper_rejected','recovered','rollback_rejected'],actions:[['tamper','Tamper with a copy'],['recover','Rehearse recovery']]}
];
const missionElements=[];let experimentBusy=false,lastEvidence='',lastExpedition=null;
for(const challenge of challenges){const card=document.createElement('details');card.className='mission';card.open=missionElements.length===0;const summary=document.createElement('summary'),tag=document.createElement('small'),title=document.createElement('strong'),count=document.createElement('span');tag.textContent=challenge.tag;title.textContent=challenge.title;count.className='mission-count';summary.append(tag,title,count);const text=document.createElement('p');text.textContent=challenge.text;const actions=document.createElement('div');actions.className='mission-actions';for(const [action,label] of challenge.actions){const button=document.createElement('button');button.dataset.experiment=action;button.textContent=label;button.addEventListener('click',async()=>{if(experimentBusy)return;experimentBusy=true;updateExperimentButtons();try{const data=await api('experiment',{action});notice(data.message);$('experiment-message').textContent=data.message;await refresh();}catch(error){notice(error.message,true);$('experiment-message').textContent=error.message;}finally{experimentBusy=false;updateExperimentButtons();}});actions.append(button);}const proofs=document.createElement('ul');proofs.className='proof-list';card.append(summary,text,actions,proofs);$('missions').append(card);missionElements.push({card,count,proofs,challenge});}
function updateExperimentButtons(){document.querySelectorAll('[data-experiment]').forEach(b=>{b.disabled=experimentBusy||!lastExpedition?.enabled||!state?.ready;});}
window.renderExpedition=function(data){const e=data.expedition;lastExpedition=e;updateExperimentButtons();if(!e)return;const proofs=e.proofs||{},total=Object.keys(proofs).length;$('proof-count').textContent=total+' / 13';$('proof-progress').value=total;$('experiment-message').textContent=e.enabled?e.message:'Experiments are disabled by this operator.';for(const m of missionElements){const n=m.challenge.proofs.filter(p=>proofs[p]).length;m.count.textContent=n+'/'+m.challenge.proofs.length;m.card.classList.toggle('complete',n===m.challenge.proofs.length);m.proofs.replaceChildren(...m.challenge.proofs.map(key=>{const li=document.createElement('li');li.className=proofs[key]?'proved':'';li.textContent=(proofs[key]?'✓ ':'○ ')+key.replaceAll('_',' ');if(proofs[key])li.title=proofs[key].detail;return li;}));}
 $('sequence-floors').textContent=(e.feed_verified?'✓ Verified feeds · ':'Trust paused · ')+Object.entries(e.floors||{}).map(([a,n])=>a+': '+n).join(' / ');
 $('lease-records').replaceChildren(...(e.records||[]).slice().reverse().map(r=>{const row=document.createElement('div');row.className='lease-row';const label=document.createElement('strong');label.textContent=r.capability.replace('region.demo.','')+' · '+r.issuer;const status=document.createElement('span');const remaining=Math.max(0,Math.ceil((Date.parse(r.expires)-Date.now())/1000));status.textContent=r.status==='active'?remaining+'s remaining':r.status;status.className=r.status;const detail=document.createElement('small');detail.textContent=r.parent?'Child of '+r.parent.slice(0,18)+'…':'Direct signed lease';row.append(label,status,detail);return row;}));
 const evidence=JSON.stringify({identity:e.identity,leases:e.records,floors:e.floors},null,2);if(evidence!==lastEvidence){lastEvidence=evidence;$('signed-evidence').textContent=evidence;}
};
$('export-evidence').addEventListener('click',()=>{if(!lastExpedition)return;const blob=new Blob([JSON.stringify({generated_at:new Date().toISOString(),world:'genesis-world-lab',player:state.player,recovery_scope:'isolated backup and authentic archived feed replay; no live gateway restart',...lastExpedition},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='genesis-mesh-proof-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
updateExperimentButtons();
window.clearExpedition=()=>{lastExpedition=null;lastEvidence='';$('proof-count').textContent='0 / 13';$('proof-progress').value=0;$('experiment-message').textContent='Sign in to start your trust expedition.';for(const id of ['signed-evidence','sequence-floors','lease-records'])$(id).replaceChildren();for(const m of missionElements){m.proofs.replaceChildren();m.count.textContent='';m.card.classList.remove('complete');}updateExperimentButtons();};
function updateTrustHud(data){const hud=document.querySelector('.trust-hud');if(!hud)return;const cells=hud.querySelectorAll('span'),lease=data?.expedition?.records?.filter(r=>r.status==='active').at(-1);for(const [i,text,label] of [[0,data?.identity?.authority?.replace('authority-','').toUpperCase()||'—','IDENTITY'],[1,lease?.issuer?.replace('authority-','').toUpperCase()||'—','SPONSOR'],[2,data?.capabilities?.includes('region.demo.enter')?'OPEN':'LOCKED','GOLD COURT']]){cells[i].textContent=text;const small=document.createElement('small');small.textContent=label;cells[i].append(small);}hud.classList.toggle('verified',!!data?.ready);}
